- type: job
  id: BotanistBiotech
  name: Ботаник Биотехники
  description: job-description-botanistb
  playTimeTracker: JobBotanistB
  startingGear: BotanistBGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
    - Biotech

- type: startingGear
  id: BotanistBGear
  equipment:
    id: BotanistBiotechPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey