- type: job
  id: HoSBiotech
  name: Глава охраны Биотех
  description: job-description-hosb
  playTimeTracker: JobHoSB
  startingGear: HoSBGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
    - SecurityBiotech
    - ArmoryBiotech
    - Biotech
    - MedBiotech

- type: startingGear
  id: HoSBGear
  equipment:
    id: HoSBiotechPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey