- type: job
  id: HoDBiotech
  name: Глава отдела Биотехники
  description: job-description-hodb
  playTimeTracker: JobHoDB
  startingGear: HoDBGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
    - HeadOfDepartmentBiotech
    - Biotech

- type: startingGear
  id: HoDBGear
  equipment:
    id: HoDBiotechPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey