- type: job
  id: MedTechB
  name: Медтехник Биотехники
  description: job-description-medtechb
  playTimeTracker: JobMedTechB
  startingGear: MedTechBGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
    - Biotech
    - MedBiotech

- type: startingGear
  id: MedTechBGear
  equipment:
    id: MedTechBPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey