- type: job
  id: OperativeBiotech
  name: Оперативник Биотехники
  description: job-description-operativeb
  playTimeTracker: JobOperativeB
  startingGear: OperativeBGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
    - Biotech
    - MedBiotech
    - ArmoryBiotech
    - SecurityBiotech
    
- type: startingGear
  id: OperativeBGear
  equipment:
    id: OperativeBiotechPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey