- type: job
  id: SquadCommanderBiotech
  name: Капитан отряда Биотехники
  description: job-description-scb
  playTimeTracker: JobSCB
  startingGear: SquadCommanderBGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
    - ArmoryBiotech
    - MedBiotech
    - Biotech

- type: startingGear
  id: SquadCommanderBGear
  equipment:
    id: SquadCommanderBiotechPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey