- type: job
  id: SecurityBiotech
  name: Охранник Биотехники
  description: job-description-secb
  playTimeTracker: JobSecB
  startingGear: SecBGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
    - Biotech
    - MedBiotech
    - SecurityBiotech

- type: startingGear
  id: SecBGear
  equipment:
    id: SecurityBiotechPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey