- type: job
  id: BuilderChief
  name: Руководитель строительной компании
  description: job-description-builder-chief
  playTimeTracker: JobBuilderChief
  startingGear: BuilderChiefGear
  icon: "JobIconPassenger"
  access:
    - Builders
    - CitizenNC

- type: startingGear
  id: BuilderChiefGear
  equipment:
    id: BuilderChiefPDA
    jumpsuit: ClothingUniformJumpsuitChiefEngineer
