- type: job
  id: TraumaTeamChief
  name: Руководитель отдела TraumaTeam
  description: job-description-traumateam-chief
  playTimeTracker: JobTraumaTeamChief
  startingGear: TraumaTeamChiefGear
  access:
    - ChiefMedicalOfficer
    - Medical
    - Chemistry

- type: startingGear
  id: TraumaTeamChiefGear
  equipment:
    id: TraumaTeamChiefPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey