- type: job
  id: TraumaTeamDoctor
  name: Врач TraumaTeam
  description: job-description-traumateam-doctor
  playTimeTracker: JobTraumaTeamDoctor
  startingGear: TraumaTeamDoctorGear
  access:
    - Medical

- type: startingGear
  id: TraumaTeamDoctorGear
  equipment:
    id: TraumaTeamDoctorPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey