- type: job
  id: EdgeRunnerSolo
  name: job-name-edgerunner-solo
  description: job-description-edgerunner-solo
  playTimeTracker: JobEdgeRunnerSolo
  startingGear: EdgeRunnerSoloGear
  icon: "JobIconPassenger"
  access:   #TODO: change access
  - Civilian


- type: startingGear
  id: EdgeRunnerSoloGear
  equipment:
    id: EdgeRunnerSoloPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey