- type: job
  id: Fixer
  name: job-name-fixer
  description: job-description-fixer
  playTimeTracker: JobFixer
  startingGear: FixerGear
  icon: "JobIconHeadOfSecurity" #TODO: change icon
  access:   #TODO: change access
  - Civilian


- type: startingGear
  id: FixerGear
  equipment:
    id: FixerPDA
    jumpsuit: ClothingUniformJumpsuitArmoredBusinessSuit
    storage: 
      back: 
      - BaseUplinkRadio20k