- type: job
  id: Reaper
  name: job-name-reaper
  description: job-description-reaper
  playTimeTracker: JobReaper
  startingGear: ReaperGear
  icon: "JobIconHeadOfSecurity" #TODO: change icon
  supervisors: job-name-hoda #TODO: change supervisors
  access:   #TODO: change access
  - Civilian

- type: startingGear
  id: ReaperGear
  equipment:
    id: ReaperPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey