- type: job
  id: Mayor
  name: Мэр
  description: job-description-mayor
  playTimeTracker: JobMayor
  startingGear: MayorGear
  icon: "JobIconHeadOfPersonnel" #TODO: заменить иконку
  access:
    - Civilian
    - NCPD
    - Government
    - Builders

- type: startingGear
  id: MayorGear
  equipment:
    id: MayorPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey