- type: job
  id: HoDMilitech
  name: job-name-hodm
  description: job-description-hodm
  playTimeTracker: JobHoDM
  startingGear: HoDMGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
  - HeadOfDepartmentMilitech
  - Militech

- type: startingGear
  id: HoDMGear
  equipment:
    id: HoDMilitechPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey