- type: job
  id: OperativeMilitech
  name: job-name-operativem
  description: job-description-operativem
  playTimeTracker: JobOperativeM
  startingGear: OperativeMGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
  - Militech
  - MedMilitech
  - ArmoryMilitech
  - SecurityMilitech


- type: startingGear
  id: OperativeMGear
  equipment:
    id: OperativeMilitechPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey