- type: job
  id: SquadCommanderMilitech
  name: job-name-scm
  description: job-description-scm
  playTimeTracker: JobSCM
  startingGear: SquadCommanderMGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
  - ArmoryMilitech
  - MedMilitech
  - Militech
  - SecurityMilitech


- type: startingGear
  id: SquadCommanderMilitechPDA
  equipment:
    id: SquadCommanderMilitechPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey