- type: job
  id: SecurityMilitech
  name: job-name-secm
  description: job-description-secm
  playTimeTracker: JobSecM
  startingGear: SecMGear
  icon: "JobIconPassenger" #TODO: change icon
  access:   #TODO: change access
  - Militech
  - MedMilitech
  - SecurityMilitech


- type: startingGear
  id: SecMGear
  equipment:
    id: SecurityMilitechPDA
    jumpsuit: ClothingUniformJumpsuitColorGrey